# Step 1: Installation and Setup

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Step 2: Data Preprocessing

In [2]:
# Import the dataset
dataset = pd.read_csv('Churn_Modelling.csv') 

In [3]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
# Selecting the independent variables
x = dataset.drop(columns=['RowNumber', 'CustomerId', 'Surname', 'Exited'], axis=1)

In [5]:
y = dataset['Exited']
# Customer is staying or leaving the bank

In [6]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [7]:
x.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [8]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Geography        10000 non-null  object 
 2   Gender           10000 non-null  object 
 3   Age              10000 non-null  int64  
 4   Tenure           10000 non-null  int64  
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64  
 7   HasCrCard        10000 non-null  int64  
 8   IsActiveMember   10000 non-null  int64  
 9   EstimatedSalary  10000 non-null  float64
dtypes: float64(2), int64(6), object(2)
memory usage: 781.4+ KB


In [9]:
x.Gender.unique(), x.Geography.unique()

(array(['Female', 'Male'], dtype=object),
 array(['France', 'Spain', 'Germany'], dtype=object))

In [10]:
# Perform one hot encoding on the dataset
x = pd.get_dummies(x, columns=['Gender', "Geography"], drop_first=True)


In [11]:
x.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Gender_Male  Geography_Germany  \
0               1        101348.88            0                  0   
1               1        112542.58            0                  0   
2               0        113931.57            0                  0   
3               0         93826.63            0                  0   
4               1         79084.10            0                  0   

   Geography_Spain  
0                0  
1                1  
2                0  
3                0  
4                1

In [12]:
# Split the dataset into training and testing set
from sklearn.model_selection import train_test_split


In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [14]:
x.shape, x_train.shape, x_test.shape

((10000, 11), (8000, 11), (2000, 11))

In [15]:
x_train.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
7389          667   34       5       0.00              2          1   
9275          427   42       1   75681.52              1          1   
2995          535   29       2  112367.34              1          1   
5316          654   40       5  105683.63              1          1   
356           850   57       8  126776.30              2          1   

      IsActiveMember  EstimatedSalary  Gender_Male  Geography_Germany  \
7389               0        163830.64            0                  0   
9275               1         57098.00            1                  1   
2995               0        185630.76            0                  0   
5316               0        173617.09            1                  0   
356                1        132298.49            0                  0   

      Geography_Spain  
7389                1  
9275                0  
2995                0  
5316                1  
356                 1

In [16]:
# import the standard scaler
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [17]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [18]:
x_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -1.09168714,
        -0.5698444 ,  1.74309049],
       [-2.30455945,  0.30102557, -1.37744033, ...,  0.91601335,
         1.75486502, -0.57369368],
       [-1.19119591, -0.94312892, -1.031415  , ..., -1.09168714,
        -0.5698444 , -0.57369368],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ...,  0.91601335,
        -0.5698444 , -0.57369368],
       [-0.62420521, -0.08179119,  1.39076231, ..., -1.09168714,
        -0.5698444 ,  1.74309049],
       [-0.28401079,  0.87525072, -1.37744033, ..., -1.09168714,
         1.75486502, -0.57369368]])

In [19]:
x_test

array([[-0.55204276, -0.36890377,  1.04473698, ..., -1.09168714,
         1.75486502, -0.57369368],
       [-1.31490297,  0.10961719, -1.031415  , ..., -1.09168714,
        -0.5698444 , -0.57369368],
       [ 0.57162971,  0.30102557,  1.04473698, ..., -1.09168714,
        -0.5698444 ,  1.74309049],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ...,  0.91601335,
        -0.5698444 ,  1.74309049],
       [-0.00566991, -0.46460796, -0.33936434, ...,  0.91601335,
         1.75486502, -0.57369368],
       [-0.79945688, -0.84742473,  1.04473698, ...,  0.91601335,
         1.75486502, -0.57369368]])

# Step 3: Model Building

In [20]:
# Creating the object(Initializing the ANN)(ANN = Artificial Neural Network)
model = tf.keras.models.Sequential()

In [21]:
print(model)

In [22]:
# Adding the input layer and the first hidden layer
# 1) units = 6 (number of neurons in the first hidden layer)
# 2) activation = 'relu' (activation function of the first hidden layer)
# 3) input_shape = (11,) (number of independent variables)

model.add(tf.keras.layers.Dense(units=6, activation='relu', input_shape=(11,)))

# Adding the second hidden layer
model.add(tf.keras.layers.Dense(units=6, activation='relu'))


In [23]:
# Adding the output layer
# 1) units = 1 (number of neurons in the output layer)
# 2) activation = 'sigmoid' (activation function of the output layer)
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [24]:
# Compiling the model
# 1) optimizer = 'adam' (algorithm to find the optimal set of weights in the neural networks)
# 2) loss = 'binary_crossentropy' (loss function within adam optimizer)
# 3) metrics = ['accuracy'] (performance metric to judge the model)

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 6)                 72        
                                                                 
 dense_1 (Dense)             (None, 6)                 42        
                                                                 
 dense_2 (Dense)             (None, 1)                 7         
                                                                 
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


# Step 4: Model Training

In [26]:
y_train

7389    0
9275    0
2995    0
5316    0
356     0
       ..
9225    0
4859    0
3264    0
9845    0
2732    1
Name: Exited, Length: 8000, dtype: int64

In [27]:
# since it it is Series we need to convert it into numpy array
y_train = y_train.to_numpy()

In [28]:
model.fit(x_train, y_train, epochs=50, batch_size=32, validation_split=0.1)

Epoch 1/50
225/225 [==============================] - 1s 2ms/step - loss: 0.6091 - accuracy: 0.7163 - val_loss: 0.5119 - val_accuracy: 0.7950
Epoch 2/50
225/225 [==============================] - 0s 1ms/step - loss: 0.4831 - accuracy: 0.7964 - val_loss: 0.4541 - val_accuracy: 0.7975
Epoch 3/50
225/225 [==============================] - 0s 1ms/step - loss: 0.4490 - accuracy: 0.8008 - val_loss: 0.4301 - val_accuracy: 0.8050
Epoch 4/50
225/225 [==============================] - 0s 1ms/step - loss: 0.4343 - accuracy: 0.8085 - val_loss: 0.4159 - val_accuracy: 0.8175
Epoch 5/50
225/225 [==============================] - 0s 1ms/step - loss: 0.4234 - accuracy: 0.8197 - val_loss: 0.4041 - val_accuracy: 0.8350
Epoch 6/50
225/225 [==============================] - 0s 2ms/step - loss: 0.4168 - accuracy: 0.8258 - val_loss: 0.3966 - val_accuracy: 0.8388
Epoch 7/50
225/225 [==============================] - 0s 1ms/step - loss: 0.4118 - accuracy: 0.8286 - val_loss: 0.3904 - val_accuracy: 0.8425
Epoch 

# Step 5: Model Evaluation and Prediction

In [29]:
# Evaluate the model
test_loss, test_accuracy = model.evaluate(x_test, y_test)

63/63 [==============================] - 1s 2ms/step - loss: 0.3306 - accuracy: 0.8630


In [30]:
test_loss, test_accuracy

(0.33064165711402893, 0.8629999756813049)

In [31]:
y_pred = model.predict(x_test)

63/63 [==============================] - 0s 1ms/step


In [32]:
y_pred

array([[0.20314021],
       [0.2875405 ],
       [0.20079519],
       ...,
       [0.22502212],
       [0.13197894],
       [0.29005763]], dtype=float32)

In [33]:
y_pred = np.argmax(y_pred, axis=1)

In [34]:
y_test , y_test.to_numpy()

(9394    0
 898     1
 2398    0
 5906    0
 2343    0
        ..
 1037    0
 2899    0
 9549    0
 2740    0
 6690    0
 Name: Exited, Length: 2000, dtype: int64,
 array([0, 1, 0, ..., 0, 0, 0], dtype=int64))

In [35]:
# import confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_test, y_pred)

array([[1595,    0],
       [ 405,    0]], dtype=int64)