In [1]:
from numpy.random import seed
seed(888)
import tensorflow as tf
tf.random.set_seed(404)

In [2]:
import os
import numpy as np
import pandas as pd


In [15]:
# Constants
X_TRAIN_PATH = 'write/digit_xtrain.csv'
Y_TRAIN_PATH = 'write/digit_ytrain.csv'
X_TEST_PATH = 'write/digit_xtest.csv'
Y_TEST_PATH = 'write/digit_ytest.csv'
NR_CLASSES = 10

In [4]:
#Get the Data
y_train_all = np.loadtxt(Y_TRAIN_PATH, delimiter=',', dtype=int)

In [5]:
y_train_all

array([5, 0, 4, ..., 5, 6, 8])

In [6]:
y_test = np.loadtxt(Y_TEST_PATH, delimiter=',', dtype=int)
x_train_all = np.loadtxt(X_TRAIN_PATH, delimiter=',', dtype=int)
x_test = np.loadtxt(X_TEST_PATH, delimiter=',', dtype=int)

In [7]:
y_test
x_train_all.shape

(60000, 784)

In [8]:
#Explore

x_train_all[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [9]:
y_test[:4]

array([7, 2, 1, 0])

In [10]:
# Data Preprocessing
x_train_all, x_test = x_train_all / 255.0, x_test / 255.0


In [11]:
values = y_train_all[:5]
values

array([5, 0, 4, 1, 9])

In [14]:
np.eye(10)[values]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
#convert target to one-hot encoding
y_train_all = np.eye(10)[y_train_all]
y_train_all.shape

(60000, 10)

In [17]:
y_test = np.eye(10)[y_test]
y_test.shape

(10000, 10)

In [18]:
#Split the data into train and validation
x_val, y_val, x_train, y_train = x_train_all[:10000], y_train_all[:10000], x_train_all[10000:], y_train_all[10000:]


In [22]:
IMAGE_WIDTH = 28
IMAGE_HEIGHT = 28
CHANNELS = 1
TOTAL_INPUTS = IMAGE_WIDTH * IMAGE_HEIGHT * CHANNELS


In [21]:
x_train.shape
x_val.shape 
y_train.shape

(50000, 10)

In [33]:
X = tf.compat.v1.placeholder(tf.float32, shape=(28,28))
Y = tf.matmul(X, X)


RuntimeError: tf.placeholder() is not compatible with eager execution.